config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  namespace :admin do
    root "static_pages#home"
    resources :categories, except: :show
    resources :books
    resources :users
    resources :reviews, only: [:index, :show, :destroy, :edit]
    resources :requests
  end
  resources :users, except: [:destroy] do
    resources :following, only: :index
    resources :followers, only: :index
    resources :reviews, only: :index
    resources :requests
  end
  resources :books, only: [:index, :show] do
    resources :reviews do
      resources :comments
    end
    resources :rates, except: :destroy
  end
  resources :relationships, only: [:create, :destroy]
  resources :favourites, only: [:create, :destroy]
  resources :readings, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :rates, only: [:create, :update]
  resources :activities, only: [:create, :destroy]
  resources :account_activations, only: [:edit]
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :category

  mount_uploader :image, PictureUploader

  has_many :reviews, dependent: :destroy
  has_many :passive_rates, class_name: Rating.name,
    foreign_key: :book_id, dependent: :destroy
  has_many :raters, through: :passive_rates, source: :user
  has_many :rates, class_name: Rating.name
  has_many :bookmarks, dependent: :destroy

  VALID_DATE_REGEX = /\A\d{4}\-(?:0?[1-9]|1[0-2])\-(?:0?[1-9]|[1-2]\d|3[01])\z/i
  validates :title, presence: true, length: {maximum: 100}, uniqueness: true
  validates :description, presence: true
  validates :publish_date, presence: true, format: { with: VALID_DATE_REGEX}
  validates :author, presence: true
  validate  :image_size

  scope :more_rate, -> do
    order(rating: :desc).limit Settings.limit_book
  end
  scope :get_books_except_current_book, ->id do
    where("id != ?", id).limit Settings.limit_book
  end
  scope :show_newest, -> do
    order(created_at: :desc).limit Settings.limit_book
  end
  scope :filter_newest, ->{order created_at: :desc}
  scope :search_by_title, ->search do
    where "title LIKE ?", "%#{search}%"
  end
  scope :filter_title_book_or_author, ->search do
    where "title LIKE ? OR author LIKE ?", "%#{search}%", "%#{search}%"
  end
  scope :search_by_category, ->category_id do
      where category_id: category_id
  end
  scope :search_name_or_author, ->search do
    filter_title_book_or_author search
  end
  scope :favourite_books, ->id do
    Book.joins("INNER JOIN bookmarks ON books.id = bookmarks.book_id")
      .where("bookmarks.user_id = ?", id).limit Settings.limit_book
  end

  private
  def image_size
    if image.size > Settings.size_image.megabytes
      errors.add :image, Settings.alert_size_image
    end
  end
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < ApplicationController
  before_action :verify_admin_access?
  before_action :load_book, except: [:create, :new, :index]
  
  def index
    @books = Book.filter_newest.paginate page: params[:page],
      per_page: Settings.per_page
  end
  
  def show
  end
  
  def new
    @book = Book.new
  end
  
  def create
    @book = Book.new book_params
    if @book.save
      flash[:success] = t "admin.created_book"
      redirect_to [:admin, :books]
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @book.update book_params
      redirect_to [:admin, :books]
    else
      render :edit
    end
  end
  
  def destroy
    if @book.destroy
      flash[:success] = t "admin.success_destroyed_book"
    else
	    flash[:success] = t "admin.unsuccess_destroyed_book"
	  end
    redirect_to [:admin, :books]
  end
  
  private
  def book_params
    params.require(:book).permit :title, :description, :publish_date, :author, :image,
      :page, :rating, :category_id
  end
  
  def load_book
    @book = Book.find_by id: params[:id]
    unless @book
	    flash[:warning] = t "error_not_exits"
	    redirect_to root_url
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :logged_in_user, except: [:show, :index]
  before_action :load_book, only: :show

  def index
    @books = Book.filter_newest.paginate page: params[:page],
      per_page: Settings.per_page
    unless params[:search].blank?
      @books = Book.search_by_title(params[:search]).filter_newest
        .paginate page:params[:page], per_page: Settings.per_page
    end
    # @books = Book.search_by_title(params[:search]).filter_newest
    # if params[:category].blank?
    #   @books = Book.filter_newest.paginate page: params[:page],
    #     per_page: Settings.per_page
    # else
    #   @category = Category.find_by id: params[:category]
    #   unless @category
    #     flash[:danger] = t "record_isnt_exist"
    #     redirect_to books_path
    #   else
    #     @books = @category.books.filter_newest.paginate page: params[:page],
    #       per_page: Settings.per_page
    #   end
    # end
  end

  def show
    if logged_in?
      @review = @book.reviews.build
      @rate = @book.raters.build
    end
    # @books_relate = @book.category.books.get_books_except_current_book(@book.id)
    #   .newest
    @reviews = @book.reviews.includes(:user, comments: :user).newest
      .paginate page: params[:page], per_page: Settings.per_page
  end

  def new

  end

  def create

  end

  def edit

  end

  def update

  end

  def destroy

  end

  private
  def load_book
    @book = Book.find_by id: params[:id]
    unless @book
      flash[:warning] = t "app.not_exits"
      redirect_to root_url
    end
  end
end

app/views/admin/books/_formbook.html.erb
<%= form_for [:admin, @book], html: {multipart: true} do |f| %>
  <%= render "shared/error_messages" , object: @book %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div>
    <%= f.label :publish_date %>
    <%= f.text_field :publish_date, class: "form-control" %>
  </div>
  <div>
    <%= f.label :author %>
    <%= f.text_field :author, class: "form-control" %>
  </div>
  <div>
    <%= f.label :image %>
    <%= f.file_field :image, accept: "image/jpeg,image/gif,image/png", class: "form-control" %>
  </div>
  <div>
    <%= f.label :page %>
    <%= f.text_field :page, class: "form-control" %>
  </div>
  <div>
    <%= f.label :rating %>
    <%= f.text_field :rating, class: "form-control" %>
  </div>
  <div>
    <%= f.label :category_id %>
    <%= f.select :category_id, Category.all.collect {|p| [ p.name, p.id ]}, include_blank: true %>
  </div>

  <div>
    <%= f.submit yield(:button_text), class: "btn btn-primary",
        id: "btn_book" %>
    <%= link_to t(".cancel"), :back, class: "btn btn-default" %>
  </div>
<% end %>

app/views/admin/books/edit.html.erb
<% provide :title, t("admin.edit_book") %>
<% provide :button_text, t("admin.edit_book") %>
<% if verify_admin_access? %>
  <h1><%= t("admin.edit_book") %></h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="form-books">
        <%= render "formbook" %>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/books/index.html.erb
<%= will_paginate @books %>
<% @books.each do |book| %>
  <div class="row">
    <div class="col-sm-1"></div>
    <div class="col-sm-10">
    <div class="well">
      <%= link_to get_image(book, "media-object"), book, class: "pull-left" %>
      <div class="media-body">
        <h4 class="media-heading"><b><%= book.title %></b></h4>
        <p class="text-right"><%= book.author %></p>
        <p><%= truncate(book.description, length: Settings.max_len_description) %>
          <%= link_to t("views.books.index.read_more"), book, class: "label label-success" %></p>
        <ul class="list-inline list-unstyled">
          <li><span><i class="glyphicon glyphicon-calendar"></i><%= book.publish_date %></span></li>
          <li>|</li>
          <li>
            <% i = 1 %>
            <% while i <= book.rating.floor do %>
              <span class="glyphicon glyphicon-star"></span>
              <% i += 1 %>
            <% end %>
            <% if book.rating.floor < Settings.max_rate %>
              <% j = 1 %>
              <% while j <= Settings.max_rate - book.rating.floor do %>
                <span class="glyphicon glyphicon-star-empty"></span>
                <% j += 1 %>
              <% end %>
            <% end %>
            <label><%= book.rating %></label>
          <li>|</li>
          </li>
          <%= link_to t("admin.edit"), edit_admin_book_path(book), class: "btn btn-primary" %>
          <li>
            <%= link_to t("admin.delete"), [:admin, book], method: :delete,
                data: {confirm: t("admin.are_you_sure")}, class: "btn btn-danger" %></li>
          <li>
            <span><i class="fa fa-facebook-square"></i></span>
            <span><i class="fa fa-twitter-square"></i></span>
            <span><i class="fa fa-google-plus-square"></i></span>
          </li>
        </ul>
      </div>
    </div>
    </div>
    <div class="col-sm-1"></div>
  </div>
  <hr>
<% end %>
<%= will_paginate @books %>

app/views/admin/books/new.html.erb
<% provide :title, t("admin.create_book") %>
<% provide :button_text, t("admin.create_book") %>
<% if verify_admin_access? %>
  <h1><%= t "admin.create_book" %></h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="form-books">
        <%= render "formbook" %>
      </div>
    </div>
  </div>
<% end %>