config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  namespace :admin do
    root "static_pages#home"
    resources :categories, except: :show
    resources :books
    resources :users
    resources :reviews, only: [:index, :show, :destroy, :edit]
    resources :requests
  end
  resources :users, except: [:destroy] do
    resources :following, only: :index
    resources :followers, only: :index
    resources :reviews, only: :index
    resources :requests
  end
  resources :books, only: [:index, :show] do
    resources :reviews do
      resources :comments
    end
    resources :rates, except: :destroy
  end
  resources :relationships, only: [:create, :destroy]
  resources :favourites, only: [:create, :destroy]
  resources :readings, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :rates, only: [:create, :update]
  resources :activities, only: [:create, :destroy]
  resources :account_activations, only: [:edit]
end

app/models/comment.rb
class Comment < ApplicationRecord
  default_scope -> {order(created_at: :desc)}

  belongs_to :user
  belongs_to :review

  validates :content, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :logged_in_user
  before_action :load_review
  before_action :load_book
  before_action :load_comment, only: [:edit, :update, :destroy]

  def create
    @comment = Comment.new comment_params
    if @comment.save
      current_user.activities.create object_id: @comment.id,
        action_type: Activity.action_types[:comment]
      respond_to do |format|
        format.js
      end
    end
  end

  def edit
    respond_to do |format|
      format.js
    end
  end

  def update
    if @comment.update_attributes comment_params
      respond_to do |format|
        format.html {redirect_to request.referrer}
        format.js
      end
    else
      render :edit
    end
  end

  def destroy
    @comment.destroy
    respond_to do |format|
      format.js
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:content).merge! user_id: current_user.id,
        review_id: params[:review_id]
    end

    def load_book
    @book = @review.book
    unless @book
      flash[:danger] = t "app.not_exits"
      redirect_to books_path
    end
  end

  def load_comment
    @comment = Comment.find_by id: params[:id]
    unless @comment
      flash[:danger] = t "app.not_exits"
      redirect_to book_path
    end
  end

  def load_review
    @review = Review.find_by id: params[:review_id]
    unless @review
      flash[:danger] = t "app.not_exits"
      redirect_to book_path
    end
  end
end

app/views/comments/_comment.html.erb
<li id="comments-<%= comment.id %>">
  <%= link_to image_tag(comment.user.avatar, class: "media-object",
  size: Settings.max_size_avatar_show_review),
  comment.user, :class => "pull-left" %>
  <span class="user"><%= t "views.comments.comment.title_comment" %>
    <%= link_to comment.user.name, comment.user %></span>
  <span class="body" id="comment_content-<%= comment.id %>">
    <%= comment.content %>
  </span>
  <span class="timestamp">
  <% if current_user?(comment.user) %>
    <%= link_to edit_book_review_comment_path(@book, comment.review_id,
    comment.id), remote: true, :class => "btn btn-warning" do %>
      <i class="glyphicon glyphicon-pencil">
        <%= t "views.comments.comment.edit_bt"%>
      </i>
    <% end %>
    <%= link_to book_review_comment_path(@book.id, comment.review_id,
    comment.id), remote: true, method: :delete,
    data: { confirm: t("views.comments.comment.confirm_del") },
    :class => "btn btn-danger" do %>
      <i class="glyphicon glyphicon-trash">
        <%= t "views.comments.comment.del_bt"%>
      </i>
    <% end %>
  <% end %>
  </span>
  <span class="timestamp">
    <%= t "views.comments.comment.time_post"%>
    <%= time_ago_in_words(comment.created_at) %>
    <%= t "views.comments.comment.ago"%>
  </span>
</li>

app/views/comments/_edit_comment_form.html.erb
<%= form_for([:book, :review, @comment], html: { multipart: true },
  remote: true) do |f| %>
  <div class="field">
    <%= f.text_area :content,
      placeholder: t("views.comments.edit_comment.placeholder_content") %>
  </div>
  <%= f.submit t("views.comments.edit_comment.sub_edit"),
    class: "btn btn-primary" %>
<% end %>

app/views/comments/_new.html.erb
<% if logged_in? %>
  <%= form_for [@book, review, Comment.new], remote: true do |f| %>
    <div class="field padding-bottom-7">
      <%= f.text_area :content, class: "form-control reset-input", required: true %>
    </div>
    <%= f.submit t("views.comments.new.send_bt"), class: "btn btn-primary"%>
  <% end %>
<% end %>

app/views/comments/create.js.erb
$("#list-comment-<%= @review.id %>").html("<%= escape_javascript(render(@review.comments)) %>");
$(".reset-input").val('');

app/views/comments/destroy.js.erb
var element = document.getElementById('comments-<%= @comment.id %>');
element.remove();

app/views/comments/edit.js.erb
$("#comment_content-<%= @comment.id %>").html('<%= j render "comments/edit_comment_form", comment: @comment %>')

app/views/comments/update.js.erb
$("#comment_content-<%= @comment.id %>").html('<%= j simple_format @comment.content %>');