config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  namespace :admin do
    root "static_pages#home"
    resources :categories, except: :show
    resources :books
    resources :users
    resources :reviews, only: [:index, :show, :destroy, :edit]
    resources :requests
  end
  resources :users, except: [:destroy] do
    resources :following, only: :index
    resources :followers, only: :index
    resources :reviews, only: :index
    resources :requests
  end
  resources :books, only: [:index, :show] do
    resources :reviews do
      resources :comments
    end
    resources :rates, except: :destroy
  end
  resources :relationships, only: [:create, :destroy]
  resources :favourites, only: [:create, :destroy]
  resources :readings, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :rates, only: [:create, :update]
  resources :activities, only: [:create, :destroy]
  resources :account_activations, only: [:edit]
end

app/views/shared/_dislike.html.erb
<%= link_to like_path(current_user.get_like(object,
  Activity.action_types[:review])),
  remote: true, method: :delete, class: "btn icon-btn" do %>
  <span class="glyphicon btn-glyphicon glyphicon-thumbs-down img-circle text-primary"></span>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t "views.shared.error_message.error" %> <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_favourite.html.erb
<div><%= hidden_field_tag :book_id, @book.id %></div>
<button type="button" class="btn btn-danger btn-circle" id="bt-favourite" value="favourite">
  <i class="glyphicon glyphicon-heart"></i>
</button>

app/views/shared/_follow.html.erb
<div><%= hidden_field_tag :followed_id, @user.id %></div>
<button type="button" class="btn btn-success btn-sm" id="btn-follow">
  <%= t"views.shared.follow.follow_bt"%>
</button>

app/views/shared/_follow_form.html.erb
<% unless current_user?user %>
  <div class="profile-userbuttons">
    <% if current_user.following?user %>
      <%= render partial: "shared/unfollow", locals: {user: user} %>
    <% else %>
      <%= render partial: "shared/follow", locals: {user: user} %>
    <% end %>
  </div>
<% end %>

app/views/shared/_like.html.erb
<%= link_to likes_path(:object_id => object.id,
  :action_type => Activity.action_types[:review]),
  remote: true, method: :post, class: "btn icon-btn" do %>
  <span class="glyphicon btn-glyphicon
    glyphicon-thumbs-up img-circle text-primary"></span>
<% end %>

app/views/shared/_list_book.html.erb
<div class="well">
  <div class="media">
    <%= link_to get_image(book, "media-object"), book, :class => "pull-left" %>
    <div class="media-body">
      <h4 class="media-heading"><%= book.title %></h4>
      <p class="text-right"><%= book.author %></p>
      <p><%= truncate(book.description, :length => Settings.max_len_description) %>
        <%= link_to t("views.books.index.read_more"), book %></p>
      <ul class="list-inline list-unstyled">
        <li><span><i class="glyphicon glyphicon-calendar"></i> <%= book.publish_date %> </span></li>
        <li>|</li>
        <span><i class="glyphicon glyphicon-comment"></i> <%= pluralize(book.reviews.count, "review") %></span>
        <li>|</li>
        <li>
          <% i = 1 %>
          <% while i <= book.rating.floor do %>
              <span class="glyphicon glyphicon-star"></span>
              <% i += 1 %>
          <% end %>
          <% if book.rating.floor < Settings.max_rate %>
              <% j = 1 %>
              <% while j <= Settings.max_rate - book.rating.floor do %>
                  <span class="glyphicon glyphicon-star-empty"></span>
                  <% j += 1 %>
              <% end %>
          <% end %>
          <label><%= book.rating %></label>
        </li>
          <span><i class="fa fa-facebook-square"></i></span>
          <span><i class="fa fa-twitter-square"></i></span>
          <span><i class="fa fa-google-plus-square"></i></span>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_rate.html.erb
<% i = 1 %>
<% while i <= Settings.max_rate do %>
  <%= link_to book_rates_path(book, num_rate: i),
    remote: true, method: :post,
    class: "btn btn-default btn-grey btn-xs" do %>
    <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
  <% end %>
  <% i += 1 %>
<% end %>

app/views/shared/_read.html.erb
<div><%= hidden_field_tag :book_id, @book.id %></div>
<button class="btn icon-btn btn-success" id="bt-read-book" value="read">
  <span class="glyphicon btn-glyphicon glyphicon-eye-open img-circle text-success" id="icon-eye"></span>
  <span id="text-button"><%= t "views.shared.read" %></span>
</button>

app/views/shared/_reading.html.erb
<div><%= hidden_field_tag :book_id, @book.id %></div>
<button class="btn icon-btn btn-success" id="bt-read-book" value="reading">
  <span class="glyphicon btn-glyphicon glyphicon-eye-close img-circle text-success" id="icon-eye"></span>
  <span id="text-button"><%= t "views.shared.reading" %></span>
</button>

app/views/shared/_stats.html.erb
<% user ||= current_user %>
<div class="profile-usermenu">
  <ul class="nav">
    <li class="active">
      <%= link_to user_following_index_path user do %>
        <i class="glyphicon glyphicon-user"></i>
        <strong id="following" class="stat">
          <%= user.following.size %>
        </strong>
        <%= t "views.shared.stat.title_following" %>
      <% end %>
    </li>
    <li class="active">
      <%= link_to user_followers_path user do %>
        <i class="glyphicon glyphicon-user"></i>
        <strong id="followers" class="stat">
          <%= user.followers.size %>
        </strong>
        <%= t "views.shared.stat.title_follower" %>
      <% end %>
    </li>
  </ul>
</div>

app/views/shared/_unfavourite.html.erb
<div><%= hidden_field_tag :book_id, @book.id %></div>
<button type="button" class="btn btn-circle" id="bt-favourite" value="unfavourite">
  <i class="glyphicon glyphicon-heart"></i>
</button>

app/views/shared/_unfollow.html.erb
<div><%= hidden_field_tag :followed_id, @user.id %></div>
<button type="button" class="btn btn-success btn-sm" id="btn-follow">
  <%= t"views.shared.unfollow.unfollow_bt"%>
</button>

app/views/shared/_user_info.html.erb
<div class="profile-sidebar">
  <div class="profile-userpic">
    <%= link_to get_image_user(user, "img-responsive"), user %>
  </div>
  <div class="profile-usertitle">
    <div class="profile-usertitle-name">
      <%= user.name %>
    </div>
    <div class="profile-usertitle-email">
      <%= user.email %>
    </div>
  </div>
  <% if logged_in? %>
    <%= render partial: "shared/follow_form", locals: {user: user} %>
    <% if current_user? user %>
      <%= form_for current_user, html: {multipart: true} do |f| %>
        <div class="profile-user-send-request">
          <%= f.file_field :avatar, accept: "image/jpeg,image/gif,image/png", class: "btn btn-info btn-sm" %>
          <%= f.submit t("views.users.show.update_image_bt") %>
        </div>
      <% end %>
      <% if verify_user_access? %>
        <%= render partial: "shared/send_request" %>
      <% end %>
    <% end %>
  <% end %>
  <%= render partial: "shared/stats", locals: {user: user} %>
</div>