config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  namespace :admin do
    root "static_pages#home"
    resources :categories, except: :show
    resources :books
    resources :users
    resources :reviews, only: [:index, :show, :destroy, :edit]
    resources :requests
  end
  resources :users, except: [:destroy] do
    resources :following, only: :index
    resources :followers, only: :index
    resources :reviews, only: :index
    resources :requests
  end
  resources :books, only: [:index, :show] do
    resources :reviews do
      resources :comments
    end
    resources :rates, except: :destroy
  end
  resources :relationships, only: [:create, :destroy]
  resources :favourites, only: [:create, :destroy]
  resources :readings, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :rates, only: [:create, :update]
  resources :activities, only: [:create, :destroy]
  resources :account_activations, only: [:edit]
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :books, dependent: :destroy

  validates :name, presence: true, length: {maximum: Settings.max_len_name},
    uniqueness: true
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
	before_action :verify_admin_access?
	before_action :load_category, except: [:create, :index, :new]
	
	def index
		@categories = Category.all.paginate page: params[:page],
			per_page: Settings.per_page
	end
	
	def show
	end
	
	def new
		@category = Category.new
	end
	
	def create
		@category = Category.new category_params
		if @category.save
			flash[:success] = t "admin.created_category"
			redirect_to [:admin, :categories]
		else
			render :new
		end
	end
	
	def edit
	end
	
	def update
		if @category.update_attributes category_params
			flash[:success] = t "admin.updated_category"
			redirect_to [:admin, :categories]
		else
			render :edit
		end
	end
	
	def destroy
		if @category.destroy
			flash[:success] = t "admin.success_destroyed_category"
		else
			flash[:success] = t "admin.unsuccess_destroyed_category"
		end
		redirect_to [:admin, :categories]
	end
	
	private
	def category_params
		params.require(:category).permit :name
	end
	
	def load_category
		@category = Category.find_by id: params[:id]
		unless @category
			flash[:warning] = t "error_not_exits"
			redirect_to root_url
		end
	end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/views/admin/categories/_formcategory.html.erb
<%= form_for [:admin, @category] do |f| %>
  <%= render "shared/error_messages", object: @category %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div>
    <%= f.submit yield(:button_text), class: "btn btn-primary",
        id: "btn_book" %>
    <%= link_to t(".cancel"), :back, class: "btn btn-default" %>
  </div>
<% end %>

app/views/admin/categories/edit.html.erb
<% provide :title, t("admin.edit_category") %>
<% provide :button_text, t("admin.edit_category") %>
<% if verify_admin_access? %>
  <h1><%= t("admin.edit_category") %></h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="form-books">
        <%= render "formcategory" %>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/categories/index.html.erb
<%= will_paginate @categories %>
<% @categories.each do |category| %>
  <div class="row">
    <div class="col-sm-1"></div>
    <div class="col-sm-10">
      <h4 class="well" style="color:green"><%= category.name %></h4>
      <ul>
        <%= link_to t("admin.edit"), edit_admin_category_path(category), class:"btn btn-primary" %>
        <%= link_to t("admin.delete"), [:admin, category], method: :delete,
            data: {confirm: t("admin.are_you_sure")}, class:"btn btn-danger" %>
      </ul>
    </div>
    <div class="col-sm-1"></div>
  </div>
  <hr>
<% end %>
<%= will_paginate @categories %>

app/views/admin/categories/new.html.erb
<% provide :title, t("admin.create_book") %>
<% provide :button_text, t("admin.create_book") %>
<% if verify_admin_access? %>
  <h1><%= t "admin.create_book" %></h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="form-books">
        <%= render "formcategory" %>
      </div>
    </div>
  </div>
<% end %>